config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'welcomes#new'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :record, only: %i[show edit update]
  
  resource :questions, only: %i[show] do
    collection do
      post :answer
      get :answer
    end
  end
  
  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
    end
  end
  
  delete '/logout', to: 'sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  unless Rails.env.production?
    namespace :development do
      get '/login', to: 'test_sessions#new', as: :login
      post '/login', to: 'test_sessions#create'
    end
  end
end
      

app/models/question.rb
class Question < ApplicationRecord
  extend OrderAsSpecified
  has_many :choices, dependent: :destroy

  has_many :categories_questions, dependent: :destroy
  has_many :categories, through: :categories_questions

  scope :random, ->(num) { includes(:choices).sample(num) }
  scope :selected_questions, lambda { |question_ids|
                               includes(:choices).where(id: question_ids).order_as_specified(id: question_ids)
                             }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :require_login

  def show
    @category = Category.find_by(name: params[:name])
    @questions = @category.questions.random(params[:random].to_i)
  end

  def answer
    return redirect_to :root if params[:question].nil?

    @category = Category.find_by(name: params[:question][:name])
    @point = Choice.selected_choice(except_name_params.values).point
    @questions = Question.selected_questions(except_name_params.keys)

    if @questions.size == 10 && current_user
      StudyRecord.create_record_and_point_up!(current_user, @category, @point)
      flash.now[:mysuccess] = t('flash.level_up') if current_user.level_up?
    elsif current_user
      current_user.point_up!(@point)
      flash.now[:mysuccess] = t('flash.level_up') if current_user.level_up?
    end
  end

  private

  def except_name_params
    params[:question].except("name")
  end
end

app/views/questions/_link_to.html.slim
= link_to t("variable.retry"),  questions_path(name: @category.name, random: @questions.size), class: "btn btn-outline-primary btn-sm my-3 me-3", style: "width: 45%;"
= link_to t("link.to_toppage"), root_path, class: "btn btn-outline-primary btn-sm my-3", style: "width: 45%;"

app/views/questions/answer.html.slim
- breadcrumb :answer, @category.name
.container

  .question-answer-title
    = t("variable.answer_mode", n: @questions.size)
    br/
    = t("variable.answer_title", name: @category.name)
  = render "link_to"      
  .your-point
    - if logged_in? && @point == 0
      = "You couldn't get experience points"
    - elsif logged_in?
      = t("variable.your_score", point: "#{@point}", denom: @questions.size * 10)
      br/
      = t("variable.got_xp", point: "#{@point}")
    
    - else 
      = t("variable.your_score", point: "#{@point}", denom: @questions.size * 10)
    
  = render "shared/answer_form",  {questions: @questions}
  = render "link_to" 
           

app/views/questions/show.html.slim
- breadcrumb :question, @category.name
.container
  .question-answer-title
    = t("variable.question_mode", n: @questions.size)
    br/
    = t("variable.question_title", name: @category.name)
  - unless @questions.size.zero?
    = form_with model: @questions, url: answer_questions_path, method: :post , local: true do |f|
      = render "shared/questions_form", {f: f, questions: @questions}

app/views/questions/study.html.slim
.title 
  = @category_name
.sub-title
  .space.cards
    - @questions.each.with_index(1) do |question, i|
      .text-start
        = "以下のコードの実行結果は回答の通りです"
      .question-content-box.mb-3
        = question.content
      .text-start 
        = "回答"
      .choice-content-box
        - question.choices.each do |choice|
          = choice.content if choice.answer == true
          
  = paginate @questions, theme: 'bootstrap-5',
                          pagination_class: "pagination-sm flex-wrap justify-content-center",
                          nav_class: "d-inline-block"