config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'welcomes#new'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :record, only: %i[show edit update]
  
  resource :questions, only: %i[show] do
    collection do
      post :answer
      get :answer
    end
  end
  
  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
    end
  end
  
  delete '/logout', to: 'sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  unless Rails.env.production?
    namespace :development do
      get '/login', to: 'test_sessions#new', as: :login
      post '/login', to: 'test_sessions#create'
    end
  end
end
      

app/views/shared/_answer_form.html.slim
- questions.each_with_index do |question, i|
  .answer-form-effect.mb-4
    .question-title
      - if ChoiceDecorator.true_choice?(i, params[:question])
        .judgment
          = "#{question.title}"
          span.correct = "正解!"
      - else
        .judgment
          = "#{question.title}"
          span.uncorrect = "不正解!"
    = render "shared/copy_button_form", i: i, question: question
    - question.choices.each do |choice|
      .form-check.choice-content-answer style=("#{'background-color: lightgreen' if choice.answer == true}")
        = radio_button_tag "#{i}","#{choice.id}",(true if ChoiceDecorator.selected_choice?(i, choice, params[:question])) , {class: "form-check-input", disabled: true}
        = label_tag "#{i}_#{choice.id}", choice.content, class: "form-check-label"
    #accordionExample.accordion
      .accordion-item
        h2#headingOne.accordion-header
          button.accordion-button aria-controls="collapse#{question.id}" aria-expanded="true" data-bs-target="#collapse#{question.id}" data-bs-toggle="collapse" type="button" 
            - if question.commentary == "まだ解説はありません"
              = "解説はありません。"
            - else 
              = "解説を見る"
        .accordion-collapse.collapse aria-labelledby="headingOne" data-bs-parent="#accordionExample" id="collapse#{question.id}"
          .accordion-body.text-start.commentary-form
            = question.commentary

app/views/shared/_chart.html.slim
= bar_chart [['[文字列]みんなの平均', all_user_average_score(1)]],
  colors: ["#b00","#0b0"],
            max: 100,
            min: 0,
            height: "100px",
            xtitle: "平均点",
            empty: "まだデータがありません"

app/views/shared/_copy_button_form.html.slim
.question-form.text-start.mb-3
  .question-content id="copyTarget-#{i}" = question.content
  button.copy-button.btn.btn-outline-primary.mt-1 onclick="onClickCopy(#{i})"
      i.fas.fa-copy.me-1
      span = "上のコードをコピー"

app/views/shared/_errors.html.slim
  -if object.errors.any? 
    .flash_error
      - object.errors.full_messages.each do |message| 
        li = message

app/views/shared/_footer.html.slim
footer
  = render 'shared/term_of_use'
  = render "shared/privacy"
  
  div
    | &copy; 2021 RubyMania

app/views/shared/_header.html.slim
header
  #top
  .header
    - if logged_in?
      h1.gradation = link_to t("dict.title"), root_path
      nav
        ul.menu.pt-2
          li = "Lv#{current_user.level}"
          li = ""
          .progress.mt-1
            .progress-bar.progress-bar-striped.progress-bar aria-valuemax="100" aria-valuemin="0" aria-valuenow="75" role="progressbar" style=("width: #{(current_user.experience_point-(current_user.level-1)*100).to_f}%")
          li = current_user.name
      nav.navbar.navbar-expand-lg.navbar-light.ms-1
        .navbar-nav
        button.navbar-toggler aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarNavAltMarkup" data-bs-toggle="collapse" type="button" 
          span.navbar-toggler-icon style="width: 15px;"
        #navbarNavAltMarkup.collapse.navbar-collapse
          ul.navbar-nav.text-end.me-2
            li.nav-item.pt-2
              = link_to t("link.record"), record_path, class: "nav-link"

            li.nav-item.pt-2
              = link_to t("link.logout"), logout_path, method: :delete, data: {confirm: t("confirm.logout?")}, class: "nav-link"
            li.nav-item.pt-2
              = link_to t("link.contact"), new_contact_path, class: "nav-link"
      
    - else
      h1.gradation = link_to t("dict.title"), root_path
      nav
        ul.menu.me-3.mt-4
          li.me-2 = link_to auth_at_provider_path(provider: :github) do
            i.fab.fa-github.mr-2
            = "Sign in with Github"
          li = link_to t("link.contact"), new_contact_path

  .breadcrumb
    = breadcrumbs separator: " &rsaquo; "

app/views/shared/_privacy.html.slim
button.btn.btn-link data-bs-target="#Modal-privacy" data-bs-toggle="modal" type="button" 
  = t("dict.pricacy")
#Modal-privacy.modal.fade aria-hidden="true" aria-labelledby="Modal-privacy" tabindex="-1" 
  .modal-dialog.modal-dialog-scrollable.modal-lg
    .modal-content
      .modal-header
        #Modal-privacy.modal-title = t("dict.pricacy")
        button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button" 
      .modal-body.text-start
        .term-sentence
          = "本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。"
        hr/
        .term-title.mb-2
          = "第1条（個人情報)"
        .term-sentence
          = "「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。"
        hr/
         
        .term-title.mb-2
          = "第2条（個人情報の収集方法）"
        .term-sentence
          = "本サービスは，ユーザーが利用登録をする際に氏名，生年月日，電話番号，メールアドレスなどの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。"
          br/
          br/
          = "本サービスは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。"
          ol
            li = "利用登録の申請に際して虚偽の事項を届け出た場合"
            li = "本規約に違反したことがある者からの申請である場合"
            li = "その他，本サービスが利用登録を相当でないと判断した場合"
        hr/
        
        .term-title.mb-2
          = "第3条（個人情報を収集・利用する目的）"
        .term-sentence
          = "本サービスが個人情報を収集・利用する目的は，以下のとおりです。"
          ol 
            li = "サービスの提供・運営のため"
            li = "ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）"
            li = "ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等の案内のメールを送付するため"
            li = "メンテナンス，重要なお知らせなど必要に応じたご連絡のため"
            li = "利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため"
            li = "ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため"
            li = "上記の利用目的に付随する目的"
        hr/  
        
        .term-title.mb-2
          = "第4条（利用目的の変更）"
        
        .term-sentence
          = "本サービスは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。"
          br/
          br/
          = "利用目的の変更を行った場合には，変更後の目的について，ユーザーに通知し，または本ウェブサイト上に公表するものとします。"
        hr/
        
        .term-title.mb-2
          = "第5条（本サービスの提供の停止等）"
          
        .term-sentence 
          = "次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。"
          ol
            li = "人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき"
            li = "公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき"
            li = "国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき"
            li = "予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき"
            ul 
              li = "利用目的に第三者への提供を含むこと"
              li = "第三者に提供されるデータの項目"
              li = "第三者への提供の手段または方法"
              li = "本人の求めに応じて個人情報の第三者への提供を停止すること"
              li = "本人の求めを受け付ける方法"
          br/
          = "前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。"
          ol
            li = "本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合"
            li = "合併その他の事由による事業の承継に伴って個人情報が提供される場合"
            li = "        個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合"
        hr/
        
        .term-title.mb-2
          = "第6条（個人情報の訂正および削除）"
        .term-sentence 
          = "ユーザーは，本サービスにて保有する自己の個人情報が誤った情報である場合には，，本サービスに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。"
          br/
          br/
          = "ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。"
          br/
          br/
          = "前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。"
        hr/

        .term-title.mb-2 
          = "第7条（個人情報の利用停止等）"
        .term-sentence 
          = "本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。"
          br/
          br/
          = "前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。"
          br/
          br/
          = "前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。"
          br/
          br/
          = "前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。"
        hr/
        
        .term-title.mb-2
          = "第8条（アクセス解析ツール）"
        .term-sentence 
          = "本サービスは，お客様のアクセス解析のために「Googleアナリティクス」を利用しています。Googleアナリティクスは，トラフィックデータの収集のためにCookieを使用しています。"
          br/
          br/    
          = "このデータは匿名で収集されており，個人を特定するものではありません。Cookieを無効にすれば，これらの情報の収集を拒否することができますので，詳しくはお使いのブラウザの設定をご確認ください。"
          br/
          br/
          = "Googleアナリティクスについて，詳しくはGoogleアナリティクス利用規約をご確認ください。"
        hr/

        .term-title.mb-2
          = "第9条（プライバシーポリシーの変更）"
        .term-sentence
          = "本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。"
          br/
          br/
          = "変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。"
      .modal-footer
        button.btn.btn-secondary data-bs-dismiss="modal" type="button"  Close

app/views/shared/_questions_form.html.slim
- questions.each_with_index do |question, i|
  .question-form.mb-4.was-validated.question-form-effect
    .question-title
      = "#{question.title}"
    .question-content.mb-4
      = question.content
    = f.radio_button "#{question.id}","question",style:"display:none"
    = f.label "question", "", class: "form-check-label", style: "display:none;"
    .invalid-feedback.text-start.mb-1
      = "選択必須"
    .valid-feedback.text-start.mb-1
      = "選択済"
      
    - question.choices.each_with_index do |choice, o|
      .form-check.choice-content-hover
        = f.radio_button "#{question.id}","#{choice.id}" , class: "form-check-input choice_#{i}_#{o}", required: "", checked: true
        = f.label "#{question.id}_#{choice.id}", choice.content, class: "form-check-label"
        = f.hidden_field :name, value: params[:name]

                
= f.submit t("submit.do_answer"), class: "btn btn-primary btn-sm mb-3", data: { confirm: t("confirm.answer?")}

app/views/shared/_term_of_use.html.slim
button.btn.btn-link data-bs-target="#Modal-term-of-use" data-bs-toggle="modal" type="button" 
  = t("dict.term")
#Modal-term-of-use.modal.fade aria-hidden="true" aria-labelledby="Modal-term" tabindex="-1" 
  .modal-dialog.modal-dialog-scrollable.modal-lg
    .modal-content
      .modal-header
        #Modal-term.modal-title = t("dict.term")
        button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button" 
      .modal-body.text-start
        .term-sentence
          = "この利用規約（以下，「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。"
        hr/
        .term-title.mb-2 
          = "第1条（適用）"
        
        .term-sentence
          = "本規約は，本サービスの利用に関わる一切の関係に適用されるものとします。"
          br/
          br/
          = "本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。"
          
          = "本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。"
        hr/
        
        .term-title.mb-2
          = "第2条（利用登録）"
        .term-sentence
          = "本サービスにおいては，登録希望者が本規約に同意の上，利用登録を申請し，利用登録が完了するものとします。"
          = "本サービスは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。"
          ol
            li = "利用登録の申請に際して虚偽の事項を届け出た場合"
            li = "本規約に違反したことがある者からの申請である場合"
            li = "その他，本サービスが利用登録を相当でないと判断した場合"
        hr/
        
        .term-title.mb-2
          = "第3条（ユーザーIDおよびパスワードの管理）"
        .term-sentence
          = "ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。"
          br/
          br/
          = "ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。"
          = "ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，故意又は重大な過失がある場合を除き，一切の責任を負わないものとします。"
        hr/
          
        .term-title.mb-2 
          = "第4条（禁止事項）"
        
        .term-sentence
          = "ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。"
          
          ol
            li = "犯罪行為に関連する行為"
            li = "本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為"
            li = "本サービス，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為"
            li = "本サービスによって得られた情報を商業的に利用する行為"
            li = "本サービスの運営を妨害するおそれのある行為"
            li = "不正アクセス，またはこれを試みる行為"
            li = "他のユーザーに関する個人情報等を収集または蓄積する行為"
            li = "不正な目的を持って本サービスを利用する行為"
            li = "本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為"
            li = "他のユーザーに成りすます行為"
            li = "本サービス上での宣伝，広告，勧誘，または営業行為"
            li = "本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為"
            li = "その他，本サービスにて不適切と判断される行為"
        hr/
        
        .term-title.mb-2
          = "第5条（本サービスの提供の停止等）"
        .term-sentence 
          = "以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。"
          
          ol
            li = "本サービスにかかるコンピュータシステムの保守点検または更新を行う場合"
            li = "地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合"
            li = "コンピュータまたは通信回線等が事故により停止した場合"
            li = "その他，本サービスの提供が困難と判断した場合"
            li = "本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。"
        hr/
        
        .term-title.mb-2 
          = "第6条（利用制限および登録抹消）"
        .term-sentence 
          = "ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。"
          
          ol 
            li = "本規約のいずれかの条項に違反した場合"
            li = "登録事項に虚偽の事実があることが判明した場合"
            li = "本サービスからの連絡に対し，一定期間返答がない場合"
            li = "その他，本サービスの利用を適当でないと判断した場合"
            li = "本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。"
        hr/

        .term-title.mb-2 
          = "第7条（退会）"
        .term-sentence
          = "ユーザーは，本サービスの定める退会手続により，本サービスから退会できるものとします。"

        .term-title.mb-2 
          = "第8条（保証の否認および免責事項）"
        .term-sentence 
          = "本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。"
          br/
          br/
          = "本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。"
          br/
          br/
          = "本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。"
        hr/
        
        .term-title.mb-2 
          = "第9条（サービス内容の変更等）"
        .term-sentence 
          = "ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。"
        hr/
        
        .term-title.mb-2 
          = "第10条（利用規約の変更）"
        .term-sentence 
          = "本サービスは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。"
        hr/
          
        .term-title.mb-2 
          = "第11条（個人情報の取扱い）"
        .term-sentence 
          = "本サービスの利用によって取得する個人情報については，プライバシーポリシーに従い適切に取り扱うものとします。"
        hr/
        
        .term-title.mb-2 
          = "第12条（通知または連絡）"
          
        .term-sentence 
          = "ユーザーと本サービスとの間の通知または連絡は，当サービスの定める方法によって行うものとします。本サービスは,ユーザーから,別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。"
        hr/
        
        .term-title.mb-2
          = "第13条（権利義務の譲渡の禁止）"
        .term-sentence 
          = "ユーザーは，当サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。"
        hr/
        
        .term-title.mb-2 
          = "第14条（準拠法・裁判管轄）"
        .term-sentence 
          = "本規約の解釈にあたっては，日本法を準拠法とします。"
          
      .modal-footer
        button.btn.btn-secondary data-bs-dismiss="modal" type="button"  Close