config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'welcomes#new'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :record, only: %i[show edit update]
  
  resource :questions, only: %i[show] do
    collection do
      post :answer
      get :answer
    end
  end
  
  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
    end
  end
  
  delete '/logout', to: 'sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  unless Rails.env.production?
    namespace :development do
      get '/login', to: 'test_sessions#new', as: :login
      post '/login', to: 'test_sessions#create'
    end
  end
end
      

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :your_dev_set, only: %i[show]
  def show
    @study_records = current_user.study_records.recent
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(params_user)
      redirect_to record_path
      flash[:mysuccess] = t('flash.success_update')
    else
      flash.now[:mydanger] = t('flash.failure_update')
      render :edit
    end
  end

  private

  def params_user
    params.require(:user).permit(:name)
  end

  def your_dev_set
    return unless current_user

    @dstr = current_user.dev(1)
    @dint = current_user.dev(2)
    @darr = current_user.dev(3)
    @dhash = current_user.dev(4)
    @dtotal = current_user.dev(5)
    @dobj = current_user.dev(6)
    @dreg = current_user.dev(7)
  end
end

app/views/records/_calendar_table.html.slim
.calendar-space.calendar-body        
  = month_calendar events: @study_records do |date, records|
    / .form-check.choice-content-answer style=("#{'background-color: lightgreen' if choice.answer == true}")
    .me-2.border-black.mt-1.small-font
      - if records.size == 0
        .little-more.p-2
          = "#{date.month}/#{date.day}"
      - elsif records.size <= 1
        .more.p-2
          = "#{date.month}/#{date.day}"
      - elsif records.size <= 5
        .good.p-2
          = "#{date.month}/#{date.day}"
      - elsif records.size > 5
        .very-good.p-2
          = "#{date.month}/#{date.day}"
  span.me-2 = "少ない"
  span.box.border-brack.little-more
  span.box.border-brack.more
  span.box.border-brack.good
  span.box.border-brack.very-good
  span = "多い"

app/views/records/_chart_space.html.slim
.space
  .text-center.mt-5
    = "#{current_user.name}さんの偏差値"
  table.table.table-sm.small-font.mt-1.table-hover
    thead
      tr
        th scope="col"
        th scope="col"  String
        th scope="col"  Integer  
        th scope="col"  Array
        th scope="col"  Hash
        th scope="col"  Total
        th scope="col"  Object
        th scope="col"  Regexp
    tbody
      -if logged_in?
        tr
          th scope="row"  Your's
          td#dstr data-json="#{@dstr.to_json}" = @dstr
          td#dint data-json="#{@dint.to_json}" = @dint
          td#darr data-json="#{@darr.to_json}" = @darr
          td#dhash data-json="#{@dhash.to_json}" = @dhash
          td#dtotal data-json="#{@dtotal.to_json}" = @dtotal
          td#dobj data-json="#{@dobj.to_json}" = @dobj
          td#dreg data-json="#{@dreg.to_json}" = @dreg

  canvas#myBarChart  height="180"            

app/views/records/_record.html.slim
table.table id="record"
  thead
    tr.small-font
      th = t("dict.date")
      th = t("dict.category")
      th = t("dict.point")
  
  tbody
    = render @study_records

app/views/records/_record_table.html.slim
table.table.space.mt-4
  tbody
    tr
      th = User.human_attribute_name(:name)
      td = current_user.name
    tr
      th = User.human_attribute_name(:level)
      td = "Lv #{current_user.level}"
    tr
      th = User.human_attribute_name(:created_at)
      td = l current_user.created_at
    tr
      th = User.human_attribute_name(:cumulative_experience_points)
      td = "#{current_user.experience_point/10 }問"
    tr
      th = User.human_attribute_name(:next_level_points)
      td = "あと#{@next_level}問"
    tr
      th = "今までの履歴"
      td
        button.modal-container.btn.btn-outline-secondary.btn-sm data-bs-target="#Modal-record" data-bs-toggle="modal" type="button" 
          = "記録を見る"
        #Modal-record.modal.fade aria-hidden="true" aria-labelledby="Modal-term" tabindex="-1" 
          .modal-dialog.modal-dialog-scrollable.modal-lg
            .modal-content
              .modal-header
                #Modal-term.modal-title.small-font = "#{current_user.name}さんの記録"
                button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button" 
              .modal-body
                = render 'record'
              .modal-footer
                button.btn.btn-secondary data-bs-dismiss="modal" type="button"  Close

app/views/records/edit.html.slim
- breadcrumb :edit_record

= render "shared/errors",{object: @user}

.title
  = t("dict.change_name")
  
= form_with model: @user, url: record_path, method: :patch, local: true do |f|
  .form-group
    = f.label :name, User.human_attribute_name(:name)
    .row.justify-content-center.mb-3
      .input-group
        .input-group-prepend
          .input-group-text
            span
              i.fas.fa-user
        = f.text_field :name, class: "form-control", placeholder: t("placeholder.name")
  = f.submit class: "btn btn-primary btn-sm"

app/views/records/show.html.slim
- breadcrumb :record
.title
  = "Your record"
= render 'calendar_table'
= render 'record_table'
= render 'chart_space'
.space         
  = link_to "名前を変更する", edit_record_path, class: "btn btn-primary btn-sm my-3"
= javascript_pack_tag "chart/dev.js"