config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'welcomes#new'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :record, only: %i[show edit update]
  
  resource :questions, only: %i[show] do
    collection do
      post :answer
      get :answer
    end
  end
  
  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
    end
  end
  
  delete '/logout', to: 'sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  unless Rails.env.production?
    namespace :development do
      get '/login', to: 'test_sessions#new', as: :login
      post '/login', to: 'test_sessions#create'
    end
  end
end
      

app/controllers/development/test_sessions_controller.rb
class Development::TestSessionsController < ApplicationController
  skip_before_action :require_login

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end
end

app/views/development/test_sessions/new.html.slim
.container
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2
      h1.my-3 開発テスト専用画面
      = form_with url: development_login_path, local: true do |f|
        .form-group.mb-3
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group.mb-3
          = f.label :password
          = f.password_field :password, class: 'form-control'
        .actions
          = f.submit 'ログイン', class: 'btn btn-primary btn-sm'